### ISSUE TITLE
SVG animation isn't working in Safari

### ISSUE THREAD

**Issue by cornellsteven** [tholman/github-corners#17]
I'll be honest, I don't know a lot about SVG compatibility, so this might be a known thing, but the animation is not working in Safari for me, but works fine in Chrome. I'm on Safari 8.0.6.

**Comment by tholman** [comment]
To do with vendor prefixes, I'd say. I left them out to be forward facing... but should perhaps put them in :/

**Comment by cornellsteven** [comment]
I suppose it depends on how much extra code it adds. The little tail wag is great, but maybe not important enough for bloat. That said, I am on the newest version of Safari (for Yosemite, at least), so it might not be a bad idea.

**Comment by tholman** [comment]
I think you're right... should probably add it!

**Comment by tholman** [comment]
Ahh, just looked through it all. Going to pass on this one, and look forward. Would involve having `@-webkit-keyframes` as well as the animations.

I think if people decide that they can't do without it, they can add it in themselves.

Tough call, really. But I feel like this is ok :)

Thanks for pointing it out!

**Comment by cornellsteven** [comment]
Yeah, that makes total sense. Good call. Thanks for looking into it!

**Comment by MikeRalphson** [comment]
Just a note probably the same issue on Microsoft Edge.

**Comment by tholman** [comment]
Actually, since 2015, support for keyframes has gone native. Safari works, and edge should work too. (http://caniuse.com/#feat=css-animation)

**Comment by MikeRalphson** [comment]
Sorry didn't realise the issue was so old! Will check if there's any reason not working in Edge for me.
