### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by dthree** [tholman/github-corners#25]
It would be cool to link to or list the sites that use this, either in a document or at the bottom of the README. Get some community action going and show people that others use it too.

If so, [you can add my site](http://vorpal.js.org).

Nice job, btw.

**Comment by tholman** [comment]
Ahh, slow on the uptake here. Not crazy about maintaining a list, since people drop in and out on occasion.

Great to see it on your site though, really looks good!

**Comment by dthree** [comment]
No problem, thanks :)
