### ISSUE TITLE
The github-corners project needs to respect antiquity

### ISSUE THREAD

**Issue by nikolas** [tholman/github-corners#6]
I like old things and I think the old github ribbons look good, plus, they are seven years old! Soon they will be 14 years old, or more. For example, look at this page: http://django-pagetree.readthedocs.org/ The ribbon fits well with the serif font.

**Comment by sotojuan** [comment]
@tholman doesn't want to replace the old ribbons nor does he think they suck (I assume). He just made new, modern ones for fun and is sharing them with us.

**Comment by tholman** [comment]
If you spend your whole life clinging to the past, you won't have an enjoyable one.

If you don't like them, don't use them. @sotojuan is right, Its not a standard... just something different :)
