### ISSUE TITLE
Demo website broken in Safari

### ISSUE THREAD

**Issue by JayBizzle** [tholman/github-corners#9]
Using Safari 8.0.6

![screen shot 2015-11-11 at 10 35 02](https://cloud.githubusercontent.com/assets/340752/11089210/0d95772a-8860-11e5-9097-a43a44130440.png)

**Comment by JayBizzle** [comment]
Probably just need to vendor prefix some CSS, specifically `display: flex` on the `.version` selector

i.e. `display: -webkit-flex;`

**Comment by tholman** [comment]
Updated the flex property... do you think you could look now - And re-open if its still messed up?

Appreciate you pointing it out, big time!

**Comment by JayBizzle** [comment]
Yep, all good :+1:

**Comment by tholman** [comment]
Cheers!

Haha, so embarrassing!
